repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.12
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.11.2
  #   hooks:
  #     - id: mypy
  #       name: mypy (backend)
  #       files: ^backend/
  #       args: ["--config-file", "backend/mypy.ini"]
  #       additional_dependencies:
  #         - fastapi
  #         - pydantic
  #         - types-requests
  #         - typing-extensions
